name: CI/CD with Sonarqube & Docker 

on:
  push:
    branches:
      -dev/gitActions

jobs:
  test_and_analyze:
    name: Run Tests & SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3