name: CI/CD with Sonarqube & Docker 

on:
  push:
    branches:
      - dev/gitActions

jobs:
  test_and_analyze:
    name: Run Tests & SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build & Test Backend with Maven
        working-directory: back
        run: mvn clean test
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      
      - name: Install Frontend dependencies
        working-directory: front
        run: npm install

      - name: Run Frontend Tests
        working-directory: front
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: SonarQube scan
        working-directory: back
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ali-aboubacar_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD

  build_and_push_frontend:
    name: Build & Push Frontend Docker Image
    runs-on: ubuntu-latest
    needs: test_and_analyze

    steps:
      - name: checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Frontend Docker Image
        working-directory: front
        run: docker build -t bobapp-front . 

      - name: Push Frontend Docker Image
        run: docker push bobapp-front

