name: CI/CD with Sonarqube & Docker 

on:
  push:
    branches:
      - dev/gitActions

jobs:
  test_and_analyze:
    name: Run Tests & SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distrubition: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build & Test Backend with Maven
        working-directory: backend
        run: mvn clean test
